// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUHMguYl9LMFvk7KU7P1dccSExkSHRjC8',
    appId: '1:711000360478:web:1ac037d02cdfb3a35b100f',
    messagingSenderId: '711000360478',
    projectId: 'elbad-parking',
    authDomain: 'elbad-parking.firebaseapp.com',
    storageBucket: 'elbad-parking.appspot.com',
    measurementId: 'G-4BJGRXWEE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKVo0XUnv2iXkQ2cCbzbKhGzlZRNmsC2E',
    appId: '1:711000360478:android:382d29fd28095bd15b100f',
    messagingSenderId: '711000360478',
    projectId: 'elbad-parking',
    storageBucket: 'elbad-parking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMPh0OatYioSpbMok1JLrP3mDinizJsmw',
    appId: '1:711000360478:ios:f70ab3ecfcb153df5b100f',
    messagingSenderId: '711000360478',
    projectId: 'elbad-parking',
    storageBucket: 'elbad-parking.appspot.com',
    iosBundleId: 'com.example.elbad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMPh0OatYioSpbMok1JLrP3mDinizJsmw',
    appId: '1:711000360478:ios:172527ed4cdfb1335b100f',
    messagingSenderId: '711000360478',
    projectId: 'elbad-parking',
    storageBucket: 'elbad-parking.appspot.com',
    iosBundleId: 'com.example.elbad.RunnerTests',
  );
}
